config/routes.rb
Rails.application.routes.draw do

  resources :cities
  
  resources :states, only: [:index, :show] do
    resources :cities
  end

  get '/patriarchs_and_matriarchs', to: 'welcome#patriarchs_and_matriarchs'
  get '/patriarchs_and_matriarchs/:id', to: 'people#show'

  resources :people
  root 'welcome#home'

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks"}

end

app/models/person.rb
require 'pry'
require 'set'

class Person < ApplicationRecord
  include Relationships::InstanceMethods
  extend Relationships::ClassMethods
  include PersonDisplay::InstanceMethods
  extend PersonDisplay::ClassMethods
  extend Validation

  has_many :child_parents, class_name: 'ChildParent', foreign_key: :person_id
  has_many :parents, through: :child_parents, class_name: 'Person', foreign_key: :child_id
  has_many :children, through: :child_parents, class_name: 'Person', foreign_key: :parent_id

  has_many :marriages, class_name: 'Marriage', foreign_key: :person_id
  has_many :spouses, through: :marriages, class_name: 'Person', foreign_key: :spouse_id

  has_many :person_cities
  has_many :cities, through: :person_cities
  has_many :states, through: :cities

  belongs_to :user, optional: true, foreign_key: :creator_id

  validates :name, :given_name, presence: true
  validate :person_has_unique_name_and_parents, :on => :create

  validates :year_of_birth, allow_blank: true, numericality: {
                                             only_integer: true,
                                             greater_than_or_equal_to: 1400,
                                             less_than_or_equal_to: Date.today.year
                                           }
  validates :year_of_death, allow_blank: true, numericality: {
                                             only_integer: true,
                                             greater_than_or_equal_to: 1400,
                                             less_than_or_equal_to: Date.today.year
                                           }


   accepts_nested_attributes_for :parents, :spouses, :children, :reject_if => :reject_person_attributes?

  def person_has_unique_name_and_parents
    if Person.find_by(given_name: given_name, name: name)
      a = Person.find_by(given_name: given_name, name: name)
      if parent_ids
        b = a.parent_ids & parent_ids
        if b.any?
          errors.add(:given_name, "a person with the same full name can't have the same parents")
        end
      end
    end
  end

  def reject_person_attributes?(attributes)
    !Person.attributes_are_valid?(attributes)
  end

  def reject_city_attributes?(attributes)
    !City.attributes_are_valid?(attributes)
  end

  def cities_attributes=(cities_attributes)
    cities_attributes.each do |i, city_attributes|
      city = City.find_or_create_by(city_attributes)
      if city.save
        self.cities << city
      end
    end
  end

 end

app/controllers/people_controller.rb
require 'pry'

class PeopleController < ApplicationController
  load_and_authorize_resource

  def index
    @people = Person.alphabetize
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @people }
    end
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    respond_to do |format|
      if @person.save
        @person.persist_relationships
        format.html { redirect_to @person, notice: 'Person was successfully created.'}
        format.json {render action: 'show', status: :created, location: @person}
      else
        format.html {render action: 'new'}
        format.json {render json: @person.errors, status: :unprocessable_entity}
      end
    end

  end

  def show
    @person = Person.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @person }
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    @person.update(person_params)
    @person.persist_relationships
    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.'}
        format.json {render action: 'show', status: :created, location: @person}
      else
        format.html {render action: 'new'}
        format.json {render json: @person.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_path
  end



  private

  def person_params
    params.require(:person).permit(:name, :given_name, :year_of_birth, :year_of_death, :creator_id, :parent_ids => [], :child_ids => [], :spouse_ids => [], :city_ids => [], :parents_attributes => [:name, :given_name, :year_of_birth, :year_of_death, :creator_id], :children_attributes => [:name, :given_name, :year_of_birth, :year_of_death, :creator_id], :spouses_attributes => [:name, :given_name, :year_of_birth, :year_of_death, :creator_id], :cities_attributes => [:name, :state_id]).reject { |k, v| v.blank? }
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_experimentform.html.erb
<%= form_for @person, :html => {:class => 'form-inline'} do |f| %>

  <% if @person.errors.any? %>
    <h2><%= pluralize(@person.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

    <%= render 'fields', :f => f %>


      <br>

  <h2><%= f.label :parent_ids, "Select Parents" %></h2>
    <%= f.collection_check_boxes(:parent_ids, Person.alphabetize, :id, :display) do |b| %>
      <div><%= b.check_box + b.text %></div>
    <% end %>
      <br>

  <h2>Or Generate New Parents</h2>
      <%= f.fields_for :parents do |parent_fields| %>
        <%= render 'fields', :f => parent_fields %>
      <% end %>

      <br>

  <h2><%= f.label :spouse_ids, "Select Spouses or Co-parents" %></h2>
    <%= f.collection_check_boxes(:spouse_ids, Person.alphabetize, :id, :display) do |b| %>
      <div><%= b.check_box + b.text %></div>
    <% end %>

      <br>

  <h2>Or Generate a New Spouse or Co-parent (You may create additional spouses later)</h2>
    <%= f.fields_for :spouses do |spouse_fields| %>
      <%= render 'fields', :f => spouse_fields %>
    <% end %>

      <br>

  <h2><%= f.label :child_ids, "Select Children" %></h2>
      <%= f.collection_check_boxes(:child_ids, Person.alphabetize, :id, :display) do |b| %>
        <div><%= b.check_box + b.text %></div>
      <% end %>

      <br>

  <h2>Or Generate a New Child (You may create additional children later)</h2>
      <%= f.fields_for :children do |child_fields| %>
        <%= render 'fields', :f => child_fields %>
        <br>
      <% end %>

      <br>

  <h2>Select the City where your Person Lived</h2>
    <div><%= f.collection_check_boxes(:city_ids, City.alphabetize, :id, :display) do |b| %></div>
      <div><%= b.check_box + b.text %></div>
    <% end %>
      <br>

  <h2>Or Create a New City (You may create additional neighborhoods later)</h2>
    <%= f.fields_for :cities do |city_fields| %>
      <%= render 'cities/fields', :f => city_fields %>
    <% end %>

  <div><%= f.submit %></div>
<% end %>

app/views/people/_fields.html.erb
<div><%= f.text_field :given_name, value: nil, :placeholder => "Given Name" %></div>
<div><%= f.text_field :name, value: nil, :placeholder => "Family Name" %></div>
<div><%= f.text_field :year_of_birth, value: nil, :placeholder => "Year of Birth (four digits)" %></div>
<div> <%= f.text_field :year_of_death, value: nil, :placeholder => "Year of Death (four digits)" %></div>
<div><%= f.hidden_field :creator_id, :value => current_user.id %></div>
<br>

app/views/people/_form.html.erb
  <%= form_for @person do |f| %>

    <% if @person.errors.any? %>
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    <div><%= f.text_field :given_name, :placeholder => "Given Name" %></div>
    <div><%= f.text_field :name, :placeholder => "Family Name" %></div>
    <div><%= f.text_field :year_of_birth, :placeholder => "Year of Birth (four digits)" %></div>
    <div> <%= f.text_field :year_of_death, :placeholder => "Year of Death (four digits)" %></div>
    <div><%= f.hidden_field :creator_id, :value => current_user.id %></div>

        <br>

    <h2><%= f.label :parent_ids, "Select Parents" %></h2>
      <%= f.collection_check_boxes(:parent_ids, Person.alphabetize, :id, :display) do |b| %>
        <div><%= b.check_box + b.text %></div>
      <% end %>
        <br>

    <h2>Or Generate New Parents</h2>
        <%= f.fields_for :parents, @person.parents.build do |parent_fields| %>
          <%= render 'fields', :f => parent_fields %>
        <% end %>

        <%= f.fields_for :parents, @person.parents.build do |parent_fields| %>
          <%= render 'fields', :f => parent_fields %>
        <% end %>

        <br>

    <h2><%= f.label :spouse_ids, "Select Spouses or Co-parents" %></h2>
      <%= f.collection_check_boxes(:spouse_ids, Person.alphabetize, :id, :display) do |b| %>
        <div><%= b.check_box + b.text %></div>
      <% end %>

        <br>

    <h2>Or Generate a New Spouse or Co-parent (You may create additional spouses later)</h2>
      <%= f.fields_for :spouses, @person.spouses.build do |spouse_fields| %>
        <%= render 'fields', :f => spouse_fields %>
      <% end %>

        <br>

    <h2><%= f.label :child_ids, "Select Children" %></h2>
        <%= f.collection_check_boxes(:child_ids, Person.alphabetize, :id, :display) do |b| %>
          <div><%= b.check_box + b.text %></div>
        <% end %>

        <br>

    <h2>Or Generate a New Child (You may create additional children later)</h2>
        <%= f.fields_for :children, @person.children.build do |child_fields| %>
          <%= render 'fields', :f => child_fields %>
          <br>
        <% end %>

        <br>

    <h2>Select the City where your Person Lived</h2>
      <div><%= f.collection_check_boxes(:city_ids, City.alphabetize, :id, :display) do |b| %></div>
        <div><%= b.check_box + b.text %></div>
      <% end %>
        <br>

    <h2>Or Create a New City (You may create additional neighborhoods later)</h2>
    <%= f.fields_for :cities, @person.cities.build do |city_fields| %>
      <%= render 'cities/fields', :f => city_fields %>
        <br>
      <% end %>

    <div><%= f.submit %></div>
  <% end %>

app/views/people/edit.html.erb
<h1>Edit <%= @person.title_display %></h1>
<%= render 'form' %>

app/views/people/index.html.erb
<h1>Index of People</h1>

<h2><%= link_to "Add a New Person", new_person_path %></h2>
<% @people.each do |person| %>
  <%= render :partial => "partials/index", locals: {path: person_path(person), item: person} %>

<% end %>

app/views/people/new.html.erb
<h1>Add a New Person</h1>
<%= render 'form' %>

app/views/people/show.html.erb
<h1><%= @person.title_display %></h1>
<h2><%= link_to "Show all People", people_path %></h2>
<h2><%= link_to "Add Another Person", new_person_path %></h2>
<% if can? :update, @person %>
  <h3><%= link_to "Edit #{@person.title_display}", edit_person_path(@person) %></h3>
<% end %>
<% if can? :destroy, @person %>
  <h3><%= link_to "Delete #{@person.title_display}", person_path(@person), method: :delete %></h3>
<% end %>

<h2>Year of Birth:</h2>

<% if @person.year_of_birth %>
  <%= @person.year_of_birth %>
<% else %>
  <%= link_to "Add Year of Birth", edit_person_path(@person) %>
<% end %>

<h2>Year of Death:</h2>

<% if @person.year_of_death %>
  <%= @person.year_of_death %>
<% else %>
  <%= link_to "Add Year of Death", edit_person_path(@person) %>
<% end %>

<h2>Cities Where <%= @person.title_display %> Lived:</h2>

<% if @person.cities.count > 0 %>
  <% @person.cities.each do |city| %>
    <%= render :partial => "partials/index", locals: {path: city_path(city), item: city} %>
  <% end %>
<% else %>
  <%= link_to "Add a City", new_city_path %>
<% end %>

<h2>Parents:</h2>
<% if @person.parents.count > 0 %>
  <% @person.parents.each do |parent| %>
    <%= render :partial => "partials/person_template", locals: {relation: parent} %>
  <% end %>
<% else %>
  <%= link_to "Add Parents", edit_person_path(@person) %>
<% end %>

<h2>Spouses and Co-parents:</h2>
<% if @person.spouses_for_display.count > 0 %>
  <% @person.spouses_for_display.each do |spouse| %>
  <%= render :partial => "partials/person_template", locals: {relation: spouse} %>
  <% end %>
<% else %>
  <%= link_to "Add a Spouse", edit_person_path(@person) %>
<% end %>

<h2>Children:</h2>
<% if @person.children.count > 0 %>
  <% @person.children.each do |child| %>
  <%= render :partial => "partials/person_template", locals: {relation: child} %>

  <% end %>
<% else %>
  <%= link_to "Add Children", edit_person_path(@person) %>
<% end %>

<h2>Siblings:</h2>
<% if @person.siblings.count > 0 %>
  <% @person.siblings.each do |sibling| %>
    <%= render :partial => "partials/person_template", locals: {relation: sibling} %>
  <% end %>
<% else %>
  <%= link_to "Add a New Person", new_person_path %>
<% end %>

<h2>Grandparents:</h2>
<% if @person.grandparents.count > 0 %>
  <% @person.grandparents.each do |grandparent| %>
    <%= render :partial => "partials/person_template", locals: {relation: grandparent} %>
  <% end %>
<% else %>
  <%= link_to "Add a New Person", new_person_path %>
<% end %>

<h2>Grandchildren:</h2>
<% if @person.grandchildren.count > 0 %>
  <% @person.grandchildren.each do |grandchild| %>
    <%= render :partial => "partials/person_template", locals: {relation: grandchild} %>
  <% end %>
<% else %>
  <%= link_to "Add a New Person", new_person_path %>
<% end %>

<h2>Aunts/Uncles:</h2>
<% if @person.aunts_and_uncles.count > 0 %>
  <% @person.aunts_and_uncles.each do |aunt_or_uncle| %>
    <%= render :partial => "partials/person_template", locals: {relation: aunt_or_uncle} %>
    <% end %>
<% else %>
  <%= link_to "Add a New Person", new_person_path %>
<% end %>

<h2>Nephews/Nieces:</h2>
<% if @person.nephews_and_nieces.count > 0 %>
  <% @person.nephews_and_nieces.each do |nephew_or_niece| %>
    <%= render :partial => "partials/person_template", locals: {relation: nephew_or_niece} %>
    <% end %>
<% else %>
  <%= link_to "Add a New Person", new_person_path %>
  <% end %>

<h2>Cousins:</h2>
<% if @person.cousins.count > 0 %>
  <% @person.cousins.each do |cousin| %>
    <%= render :partial => "partials/person_template", locals: {relation: cousin} %>
  <% end %>
<% else %>
  <%= link_to "Add a New Person", new_person_path %>
<% end %>