config/routes.rb
Rails.application.routes.draw do

  resources :cities
  
  resources :states, only: [:index, :show] do
    resources :cities
  end

  get '/patriarchs_and_matriarchs', to: 'welcome#patriarchs_and_matriarchs'
  get '/patriarchs_and_matriarchs/:id', to: 'people#show'

  resources :people
  root 'welcome#home'

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks"}

end

app/models/state.rb
class State < ApplicationRecord

  has_many :cities
  has_many :person_cities, through: :cities
  has_many :people, through: :person_cities

  validates :name, presence: true

  def display
    "#{self.name}"
  end

  def self.alphabetize
    self.order(:abbreviation)
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  load_and_authorize_resource

  def index
    @states = State.alphabetize
    respond_to do |format|
      format.json { render json: @states }
      format.html { render :index }

    end
  end

  def show
    @states = State.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @state }
    end
  end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/index.html.erb
<h1>Index of States</h1>

<% @states.alphabetize.each do |state| %>
  <%= render :partial => "partials/index", locals: {path: state_path(state), item: state} %>
  <% if state.cities.count > 0 %>
    (<%= state.name %> has cities)
  <% else %>
    (no cities entered yet. <%= link_to "add a city to #{state.name}", new_city_path %>)
  <% end %>

<% end %>

app/views/states/show.html.erb
<h1>Cities in <%= @state.display %></h1>

<h2>Add A City:</h2>
<%= form_for @state.cities.build, :html => {:id => "add_city_to_state"} do |f| %>
  <div><%= f.text_field :name, value: nil, :placeholder => "Name", id: "name_input" %></div>
  <%= f.hidden_field :state_id, :value => @state.id %>
  <div><%= f.submit "Add City" %></div>
<% end %>

<div id="new_city"></div>

<div id="show_cities"><% @state.cities.alphabetize.each do |city| %>
  <h3><%= link_to city.name, city_path(city) %></h3>

<% end %></div>