config/routes.rb
Rails.application.routes.draw do

  resources :cities
  
  resources :states, only: [:index, :show] do
    resources :cities
  end

  get '/patriarchs_and_matriarchs', to: 'welcome#patriarchs_and_matriarchs'
  get '/patriarchs_and_matriarchs/:id', to: 'people#show'

  resources :people
  root 'welcome#home'

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks"}

end

app/models/city.rb
class City < ApplicationRecord
  extend Validation
  
  belongs_to :state
  has_many :person_cities
  has_many :people, through: :person_cities

  validates :name, :state_id, presence: true
  validates :name, uniqueness: { scope: :state_id }

  def display
    "#{self.name} (#{self.state.name})"
  end

  def self.alphabetize
    self.order(:name)
  end

  def save_associations
    respond_to do |format|
      if self.save
        format.html { redirect_to person_path(self), notice: 'City was successfully created.'}
        format.json {render action: 'show', status: :created, location: city_path(self)}
      else
        format.html {render action: 'new'}
        format.json {render json: self.errors, status: :unprocessable_entity}
      end
    end
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  load_and_authorize_resource

  def index
    @cities = City.alphabetize
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @cities }
    end
  end

  def new
    @city = City.new
    @city.people.build
  end

  def create
    @city = City.new(city_params)
    respond_to do |f|
      if @city.save
        f.json {render :json => @city}
        f.html { redirect_to @city, notice: 'City was successfully created.'}
      else
        format.html {render action: 'new'}
        format.json {render json: @city.errors, status: :unprocessable_entity}
      end
    end
  end

  def show
    @city = City.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @city }
    end
  end

  def edit
    @city = City.find(params[:id])
  end

  def update
    @city = City.find(params[:id])
    @city.update(city_params)
    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully updated.'}
        format.json {render action: 'show', status: :created, location: @city}
      else
        format.html {render action: 'new'}
        format.json {render json: @city.errors, status: :unprocessable_entity}
      end
    end
  end

  private

  def city_params
    params.require(:city).permit(:name, :state_id, :person_ids => []).reject { |k, v| v.blank? }
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_fields.html.erb
<div><%= f.text_field :name, value: nil, :placeholder => "Name" %></div>
<div><%= f.collection_select :state_id, State.alphabetize, :id, :abbreviation, :selected => nil, include_blank: "Select State" %></div>
<br>

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>

  <% if @city.errors.any? %>
    <h2><%= pluralize(@city.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

    <%= render 'fields', :f => f %>


      <br>

  <h2><%= f.label :people, "Select People who Lived in this City" %></h2>
  <%= f.collection_check_boxes(:person_ids, Person.alphabetize, :id, :display) do |b| %>
    <div><%= b.check_box + b.text %></div>
  <% end %>
       <br>
  <h2><%= link_to "Or Add a New Person", new_person_path %></h2>
  <h3>(You can add a new city on that page also)</h3>
  <div><%= f.submit %></div>
<% end %>

app/views/cities/edit.html.erb
<h1><%= "Edit #{@city.display}" %></h1>
<%= form_for(@city) do |f| %>

  <% if @city.errors.any? %>
    <h2><%= pluralize(@city.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

    <%= render 'fields', :f => f %>


      <br>

  <h2><%= f.label :people, "Select People who Lived in this City" %></h2>
  <%= f.collection_check_boxes(:person_ids, Person.alphabetize, :id, :display) do |b| %>
    <div><%= b.check_box + b.text %></div>
  <% end %>
       <br>
  <h2><%= link_to "Or Add a New Person", new_person_path %></h2>
  <h3>(You can add a new city on that page also)</h3>
  <div><%= f.submit %></div>
<% end %>

app/views/cities/index.html.erb
<h1>Index of Cities</h1>
<h2><%= link_to "Add a New City", new_city_path %></h2>
<% @cities.each do |city| %>
<h3><%= render :partial => "partials/index", locals: {path: city_path(city), item: city} %> </h3>
<% end %>

app/views/cities/new.html.erb
<h1>Add a New City</h1>
<%= render 'form' %>

app/views/cities/show.html.erb
<h1><%= @city.name %>, <%= link_to "#{@city.state.name}", @city.state  %></h1>

<h2>People who Lived in <%= @city.name %>:</h2>
  <% if @city.people.count > 0 %>
    <% @city.people.alphabetize.each do |person| %>
      <%= render :partial => "partials/index", locals: {path: person_path(person), item: person} %>
    <% end %>
  <% else %>
    <h3>There are no people in the database who lived in <%= @city.name %></h3>
  <% end %>
  <h3><%= link_to "Add a Person", new_person_path %></h3>

  <h2><%= link_to "Edit #{@city.display}", edit_city_path(@city) %></h2>
  <h2><%= link_to "Add Another City", new_city_path %></h3>
  <h2><%= link_to "Show all Cities", cities_path %></h2>